# Site settings
title: vorteil.io
email: vorteil-io@googlegroups.com
url: https://sisatech.github.io
description: "Quickly build apps as independent, bootable virtual machines for rapid deployment and immutable infrastructure."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#FFF'
  links: '#2396d8'

# Footer settings
footer: Sisatech Pty Ltd

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/vorteilos?lang=en
  - title: facebook
    url: https://www.facebook.com/sisatech2013/
  - title: github
    url: https://github.com/sisatech/vcli

# Build settings
markdown: kramdown
permalink: pretty
